---
- hosts: all
  become: yes
  name: Configure all servers
  pre_tasks:
    - name: Create directories
      file:
        path: "/data"
        state: directory
        
    - name: Setup base system
      import_tasks: tasks/base.yml

  roles:
    - role: geerlingguy.docker
      docker_users:
        - administrator
  tasks:
    - name: Gather facts (always, even with tags)
      ansible.builtin.setup:
      tags: always

    

  

    