---
- hosts: cloud
  become: yes
  vars:
    traefik_host: "vps02.comprofix.com"

  tasks:
    - name: Deploy traefik
      import_tasks: tasks/traefik.yml

    - name: Deploy postgres
      import_tasks: tasks/postgres.yml

    - name: Deploy Vaultwarden
      import_tasks: tasks/vaultwarden.yml
      tags: vaultwarden_install

    - name: Deploy gitea
      import_tasks: tasks/gitea.yml
      tags: gitea_install

    - name: Gotify
      import_tasks: tasks/gotify.yml
      tags: gotify_install