---
- hosts: all
  name: Configure all servers
  tasks:
    - name: Gather facts if run with tags
      ansible.builtin.setup:
      when: (ansible_run_tags | length) > 0
  tags: always

- hosts: jellyfin
  become: yes
  tasks:
    - include_tasks: tasks/base.yml
  tags: base_install

- hosts: cloud
  become: yes
  roles:
    - role: oefenweb.fail2ban
      vars:
        fail2ban_services:
          - name: sshd
            port: 22
            maxretry: 3
            bantime: -1
      tags: fail2ban

    - role: docker
      tags: docker_install

    - name: traefik
      vars:
        traefik_host: traefik01.comprofix.com
      tags: traefik_install

  tasks:
    - name: Deploy Vaultwarden
      import_tasks: tasks/vaultwarden.yml
      tags: vaultwarden_install

    - name: Deploy gitea
      import_tasks: tasks/gitea.yml
      tags: gitea_install

    - name: Gotify
      import_tasks: tasks/gotify.yml
      tags: gotify_install
  tags: cloud_install

- hosts: docker
  become: yes
  pre_tasks:
    - name: Connect iscsi
      import_tasks: tasks/iscsi.yml
      tags: iscsi_connect

  roles:
    - role: oefenweb.fail2ban
      vars:
        fail2ban_services:
          - name: sshd
            port: 22
            maxretry: 3
            bantime: -1
      tags: fail2ban

    - role: docker
      tags: docker_install
    - role: nfs
      mounts:
        - name: Data share
          path: /mnt/nfs/data
          src: truenas.comprofix.xyz:/mnt/datapool/data
      tags: nfs_install
    - role: traefik
      vars:
        traefik_host: traefik02.comprofix.xyz
      tags: traefik_install
  tasks:
    - name: Deploy comprofix.com website
      import_tasks: tasks/comprofix.com.yml
      tags: comprofix_install

    - name: Deploy iDrac Fan Controller
      import_tasks: tasks/idrac.yml
      tags: idrac_install

    - name: Deploy MariaDB
      import_tasks: tasks/mariadb.yml
      tags: mariadb_install

    - name: Deploy InvoiceNinja
      import_tasks: tasks/invoiceninja.yml
      tags: invoiceninja_install

    - name: Deploy Homepage
      import_tasks: tasks/homepage.yml
      tags: homepage_install

    # - name: Deploy osTicket
    #   import_tasks: tasks/osticket.yml
    #   tags: osticket_install

    - name: Deploy speedtest-tracker
      import_tasks: tasks/speedtest.yml
      tags: speedtest_install

    - name: Deploy dozzle
      import_tasks: tasks/dozzle.yml
      tags: dozzle_install

    - name: Deploy jellyseerr
      import_tasks: tasks/jellyseerr.yml
      tags: jellyseerr_install

    - name: Deploy lidarr
      import_tasks: tasks/lidarr.yml
      tags: lidarr_install

    - name: Deploy prowlarr
      import_tasks: tasks/prowlarr.yml
      tags: prowlarr_install

    - name: Deploy radarr
      import_tasks: tasks/radarr.yml
      tags: radarr_install

    # - name: Deploy readarr
    #   import_tasks: tasks/readarr.yml
    #   tags: readarr_install

    - name: Deploy sonarr
      import_tasks: tasks/sonarr.yml
      tags: sonarr_install

    - name: Deploy sabnzbd
      import_tasks: tasks/sabnzbd.yml
      tags: sabnzbd_install

    - name: Deploy mealie
      import_tasks: tasks/mealie.yml
      tags: mealie_install

    - name: Deploy pyKMS
      import_tasks: tasks/pykms.yml
      tags: pykms_install

    - name: Deploy mediawiki
      import_tasks: tasks/mediawiki.yml
      tags: mediawiki_install

    - name: Deploy traggo
      import_tasks: tasks/traggo.yml
      tags: traggo_install

    - name: Deploy gitea-runner-homelab
      import_tasks: tasks/gitea-runner-homelab.yml
      tags: gitea-runner-homelab_install

  tags: dockerserver_install

- hosts: omada
  become: yes
  pre_tasks:
    - name: Update packages
      import_tasks: tasks/base.yml

    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "/data"
  roles:
    - role: docker
      tags: docker_install
    - role: nfs
      mounts:
        - name: Data share
          path: /data
          src: truenas.comprofix.xyz:/mnt/datapool/docker
      tags: nfs_install
  tasks:
    - name: Deploy Dozzle Agent
      import_tasks: tasks/dozzle-agent.yml
      tags: dozzle-agent_install

    - name: Deploy Omada
      import_tasks: tasks/omada.yml
      tags: omada_install
  tags: omada_lxc_install
