---
- hosts: omada
  become: yes
  roles:
    - role: nfs
      mounts:
        - name: Data share
          path: /data
          src: truenas.comprofix.xyz:/mnt/datapool/docker
      tags: nfs_install
  tasks:
    - name: Deploy Dozzle Agent
      import_tasks: tasks/dozzle-agent.yml
      tags: dozzle-agent_install

    - name: Deploy Omada
      import_tasks: tasks/omada.yml
      tags: omada_install
  tags: omada_lxc_install
