- name: Create the comprofix.com container
  docker_container:
    name: comprofix.com
    image: git.comprofix.com/mmckinnon/comprofix.com:latest
    restart_policy: unless-stopped
    recreate: true
    networks:
      - name: proxy
    labels:
      traefik.enable: "true"
      traefik.http.routers.comprofix.rule: "Host(`comprofix.com`)"
      traefik.http.routers.comprofix.entrypoints: "https"
      traefik.http.routers.comprofix.tls: "true"
      traefik.http.services.comprofix.loadbalancer.server.port: "80"