---
- name: Create/Update the dozzle container
  docker_container:
    name: dozzle
    image: amir20/dozzle:v8.14.5
    restart_policy: unless-stopped
    networks:
      - name: proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # env:
    #   DOZZLE_LEVEL: "trace"
    #   DOZZLE_REMOTE_AGENT: "omada-lxc.comprofix.xyz:7007"
    labels:
      traefik.enable: "true"
      traefik.http.routers.dozzle.rule: "Host(`devdozzle.comprofix.xyz`)"
      traefik.http.routers.dozzle.entrypoints: "https"
      traefik.http.routers.dozzle.tls: "true"
      traefik.http.services.dozzle.loadbalancer.server.port: "8080"
      traefik.http.services.dozzle.loadbalancer.server.scheme: "http"
    pull: true
    recreate: true


