---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ data_folder }}/dozzle"
    - "{{ data_folder }}/dozzle/config"

- name: Create the dozzle container
  docker_container:
    name: dozzle
    image: amir20/dozzle:v8.13.12
    restart_policy: unless-stopped
    recreate: true
    networks:
      - name: proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env:
      DOZZLE_LEVEL: "trace"
      DOZZLE_REMOTE_AGENT: "omada-lxc.comprofix.xyz:7007"
    labels:
      traefik.enable: "true"
      traefik.http.routers.dozzle.rule: "Host(`dozzle.comprofix.xyz`)"
      traefik.http.routers.dozzle.entrypoints: "https"
      traefik.http.routers.dozzle.tls: "true"
      traefik.http.services.dozzle.loadbalancer.server.port: "8080"
      traefik.http.services.dozzle.loadbalancer.server.scheme: "http"
