---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/data/gitea"
    - "/data/gitea/data"
    - "/data/gitea/db"

- name: Pull dozzle image
  community.docker.docker_image:
    name: mysql
    tag: 9
    source: pull
  register: docker_image

- name: Create MySQL DB for Gitea
  docker_container:
    name: gitea_db
    image: "{{ docker_image.image.RepoTags[0] }}"
    restart_policy: unless-stopped
    networks:
      - name: proxy
    env:
      MYSQL_ROOT_PASSWORD: "{{ gitea_db_root_password }}"
      MYSQL_USER: "{{ gitea_db_user }}"
      MYSQL_PASSWORD: "{{ gitea_db_password }}"
      MYSQL_DATABASE: gitea
    volumes:
      - "/data/gitea/db:/var/lib/mysql"
  when: docker_image.changed
  register: container_mysql

- name: Pull dozzle image
  community.docker.docker_image:
    name: gitea/gitea
    tag: 1.24
    source: pull
  register: docker_image

- name: Create the Gitea container
  docker_container:
    name: gitea
    image: "{{ docker_image.image.RepoTags[0] }}"
    restart_policy: unless-stopped
    networks:
      - name: proxy
    ports:
      - "2222:22"
    env:
      PUID: "1001"
      PGID: "1001"
      TZ: "Australia/Brisbane"
    volumes:
      - "/data/gitea/data:/data"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      traefik.enable: "true"
      traefik.http.routers.gitea.rule: "Host(`git.comprofix.com`)"
      traefik.http.routers.gitea.entrypoints: "https"
      traefik.http.routers.gitea.tls: "true"
      traefik.http.routers.gitea.service: "gitea"
      traefik.http.services.gitea.loadbalancer.server.port: "3000"
  when: docker_image.changed
  register: container_gitea

- name: Create folders
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/data/gitea-runner"
    - "/data/gitea-runner/config"

- name: Check that config.yaml exists
  stat:
    path: "/data/gitea-runner/config/config.yaml"
  register: configyaml

- name: Create config.yaml file
  file:
    path: "/data/gitea-runner/config/config.yaml"
    state: touch
    mode: "0600"
    access_time: preserve
    modification_time: preserve
  when: configyaml.stat.exists == False

- name: Pull act-runner image
  community.docker.docker_image:
    name: gitea/act_runner
    tag: 0.2.13
    source: pull
  register: docker_image

- name: Create the gitea-runner container
  docker_container:
    name: gitea-runner
    image: "{{ docker_image.image.RepoTags[0] }}"
    restart_policy: unless-stopped
    volumes:
      - "/etc/resolv.conf:/etc/resolv.conf:ro"
      - /var/run/docker.sock:/var/run/docker.sock
      - "/data/gitea-runner/config/config.yaml:/config.yaml"
      - "/etc/hosts:/etc/hosts:ro"
    env:
      CONFIG_FILE: "/config.yaml"
      GITEA_INSTANCE_URL: "https://git.comprofix.com"
      GITEA_RUNNER_REGISTRATION_TOKEN: "{{ GITEA_RUNNER_TOKEN }}"
      GITEA_RUNNER_NAME: "gtar-runner"
      GITEA_RUNNER_LABELS: "alpine-latest:docker://git.comprofix.com/mmckinnon/alpine-runner:latest,ubuntu-latest:docker://node:22-trixie,gtar-latest:docker://git.comprofix.com/mmckinnon/debian-latest:latest"
  when: docker_image.changed
  register: container_gitea_runner

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/data/opengist"

- name: Pull dozzle image
  community.docker.docker_image:
    name: ghcr.io/thomiceli/opengist
    tag: 1.11
    source: pull
  register: docker_image

- name: Create the opengist container
  docker_container:
    name: opengist
    image: "{{ docker_image.image.RepoTags[0] }}"
    restart_policy: unless-stopped
    networks:
      - name: proxy
    volumes:
      - "/data/opengist:/opengist"
    env:
      OG_GITEA_CLIENT_KEY: "{{ OG_GITEA_KEY }}"
      OG_GITEA_SECRET: "{{ OG_GITEA_SECRET }}"
      # URL of the Gitea instance. Default: https://gitea.com/
      OG_GITEA_URL: "https://git.comprofix.com"
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
    labels:
      traefik.enable: "true"
      traefik.http.routers.opengist.rule: "Host(`gist.comprofix.com`)"
      traefik.http.routers.opengist.entrypoints: "https"
      traefik.http.routers.opengist.tls: "true"
      traefik.http.routers.opengist.service: "opengist"
      traefik.http.services.opengist.loadbalancer.server.port: "6157"
  when: docker_image.changed
  register: container_opengist
