- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ data_folder }}/gitea-runner"
    - "{{ data_folder }}/gitea-runner/config"

- name: Check that config.yaml exists
  stat:
    path: "{{ data_folder }}/gitea-runner/config/config.yaml"
  register: configyaml

- name: Create config.yaml file
  file:
    path: "{{ data_folder }}/gitea-runner/config/config.yaml"
    state: touch
    mode: "0600"
    access_time: preserve
    modification_time: preserve
  when: configyaml.stat.exists == False

- name: Create the gitea-runner container
  docker_container:
    name: gitea-runner
    image: gitea/act_runner:0.2.13
    restart_policy: unless-stopped
    recreate: true
    # dns_servers:a
    #   - 10.10.10.1
    #   - 127.0.0.11
    volumes:
      - "/etc/resolv.conf:/etc/resolv.conf:ro"
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ data_folder }}/gitea-runner/config/config.yaml:/config.yaml"
      - "/etc/hosts:/etc/hosts:ro"
    env:
      CONFIG_FILE: "/config.yaml"
      GITEA_INSTANCE_URL: "https://git.comprofix.com"
      GITEA_RUNNER_REGISTRATION_TOKEN: "{{ GITEA_RUNNER_TOKEN }}"
      GITEA_RUNNER_NAME: "homelab-runner"
      GITEA_RUNNER_LABELS: "alpine-latest:docker://{{ alpine_latest_image }},ubuntu-latest:docker://{{ ubuntu_latest_image }},homelab-latest:docker://{{ debian_latest_image }}"
