---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/data/homepage"
    - "/data/homepage/config"

- name: Get dashboard-icons
  git:
    repo: https://github.com/walkxcode/dashboard-icons.git
    dest: /data/dashboard-icons
    update: yes

- name: Pull docker image
  community.docker.docker_image:
    image: ghcr.io/gethomepage/homepage
    tag: v1.5.0
    source: pull
  register: docker_image


- name: Create the homepage container
  docker_container:
    name: homepage
    image: "{{ docker_image.image.RepoTags[0] }}"
    restart_policy: unless-stopped
    networks:
      - name: proxy
    env:
      LOG_LEVEL: debug
      HOMEPAGE_ALLOWED_HOSTS: homepage.comprofix.xyz
    volumes:
      - "/data/homepage/config:/app/config"
      - "/data/dashboard-icons:/app/public/icons"
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: "true"
      traefik.http.routers.homepage.rule: "Host(`homepage.comprofix.xyz`)"
      traefik.http.routers.homepage.entrypoints: "https"
      traefik.http.routers.homepage.tls: "true"
      traefik.http.routers.homepage.service: "homepage"
      traefik.http.services.homepage.loadbalancer.server.port: "3000"
  when: docker_image.changed
  register: container_homepage
