---
- name: Pull docker image
  community.docker.docker_image:
    name: ghcr.io/tigerblue77/dell_idrac_fan_controller
    tag: latest
    source: pull
    force_source: true
    force_tag: true
  register: docker_image

- name: Create the Dell_R730xd Fan Contoller container
  docker_container:
    name: Dell_R730xd
    image: "{{ docker_image.image.RepoTags[0] }}"
    restart_policy: unless-stopped
    env:
      IDRAC_HOST: "10.10.10.105"
      IDRAC_USERNAME: "root"
      IDRAC_PASSWORD: "calvin"
      FAN_SPEED: "50"
      CPU_TEMPERATURE_THRESHOLD: "80"
      CHECK_INTERVAL: "60"
      DISABLE_THIRD_PARTY_PCIE_CARD_DELL_DEFAULT_COOLING_RESPONSE: "true"
  when: docker_image.changed
  register: container_idrac
