---    
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/data/jellyseerr"
    - "/data/jellyseerr/config"

- name: Pull docker image
  community.docker.docker_image:
    image: fallenbagel/jellyseerr:2.7.3 
    tag: 2.7.3
    source: pull
  register: docker_image

- name: Create the jellyseerr container
  docker_container:
    name: jellyseerr
    image: "{{ docker_image.image.RepoTags[0] }}"
    restart_policy: unless-stopped
    networks:
      - name: proxy
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
    volumes:
      - "/data/jellyseerr/config:/app/config"
    labels:
      traefik.enable: "true"
      traefik.http.routers.jellyseerr.rule: "Host(`jellyseerr.comprofix.xyz`)"
      traefik.http.routers.jellyseerr.entrypoints: "https"
      traefik.http.routers.jellyseerr.tls: "true"
      traefik.http.services.jellyseerr.loadbalancer.server.port: "5055"
  when: docker_image.changed
  register: container_jellyseerr