---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/data/mariadb"
    - "/data/mariadb/config"

- name: Pull docker image
  community.docker.docker_image:
    image: ghcr.io/linuxserver/mariadb
    tag: 11.4.8
    source: pull
  register: docker_image
  
- name: Create the mariadb container
  docker_container:
    name: "mariadb"
    image: "{{ docker_image.image.RepoTags[0] }}"
    restart_policy: unless-stopped
    ports:
      - 3306:3306
    env:
      PUID: "0"
      PGID: "0"
      MYSQL_ROOT_PASSWORD: "{{MYSQL_ROOT_PASSWORD}}"
      TZ: "Australia/Brisbane"
    volumes:
      - "/data/mariadb/config:/config"
  when: docker_image.changed
  register: container_mariadb
    