---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ data_folder }}/mssql"
    - "{{ data_folder }}/mssql/data"
    - "{{ data_folder }}/mssql/log"
    - "{{ data_folder }}/mssql/secrets"

- name: Create the mssql container
  docker_container:
    name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest@sha256:b1395aa51b4ec39981883560f1379ea9eba2a1c0719bf8e6477902769316bb79
    restart_policy: unless-stopped
    recreate: true
    ports:
      - 1433:1433
    env:
      PUID: "1000"
      PGID: "1000"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      SA_PASSWORD: "{{ SA_PASSWORD }}"
    volumes:
      - "{{ data_folder }}/mssql/data:/var/opt/mssql/data"
      - "{{ data_folder }}/mssql/log:/var/opt/mssql/log"
      - "{{ data_folder }}/mssql/secrets:/var/opt/mssql/secrets"