---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ data_folder }}/mssql"
    - "{{ data_folder }}/mssql/data"
    - "{{ data_folder }}/mssql/log"
    - "{{ data_folder }}/mssql/secrets"

- name: Create the msqql container
  docker_container:
    name: msqql
    image: mcr.microsoft.com/mssql/server:2025-latest@sha256:2c80e548ef65fb65a8ca23c3a74ed60e0964ea709f46d07c97ccaf7c437e2cc6
    restart_policy: unless-stopped
    recreate: true
    ports:
      - 1433:1433
    env:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      SA_PASSWORD: "{{ SA_PASSWORD }}"
    volumes:
      - "{{ data_folder }}/mssql/data:/var/opt/mssql/data"
      - "{{ data_folder }}/mssql/log:/var/opt/mssql/log"
      - "{{ data_folder }}/mssql/secrets:/var/opt/mssql/secrets"