---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ data_folder }}/omada"
    - "{{ data_folder }}/omada/data"
    - "{{ data_folder }}/omada/logs"

- name: Create the omada container
  docker_container:
    name: omada
    image: mbentley/omada-controller:5.15
    restart_policy: unless-stopped
    recreate: true
    network_mode: host
    volumes:
      - "{{ data_folder }}/omada/data:/opt/tplink/EAPController/data"
      - "{{ data_folder }}/omada/logs:/opt/tplink/EAPController/logs"
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
