---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/data/postgres"
    - "/data/postgres/data"

- name: Pull docker image
  community.docker.docker_image:
    image: postgres
    tag: 17.0-alpine
    source: pull
  register: docker_image

- name: Create the postgres container
  docker_container:
    name: postgres
    image: "{{ docker_image.image.RepoTags[0] }}"
    restart_policy: unless-stopped
    ports:
      - 5432:5432
    env:
      POSTGRES_PASSWORD: "{{POSTGRES_PASSWORD}}"
    volumes:
      - /data/postgres/data:/var/lib/postgresql/data
  when: docker_image.changed
  register: container_postgres

