---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/data/pykms"
    - "/data/pykms/db"

- name: Pull docker image
  community.docker.docker_image:
    name: ghcr.io/py-kms-organization/py-kms
    tag: latest
    source: pull
    force_source: true
    force_tag: true
  register: docker_image
  
- name: Create the pykms container
  docker_container:
    name: pykms
    image: "{{ docker_image.image.RepoTags[0] }}"
    restart_policy: unless-stopped
    ports:
      - "1688:1688"
    env:
      IP: "0.0.0.0"
      SQLITE: "true"
      HWID: "RANDOM"
      LOGLEVEL: "INFO"
    volumes:
      - "/data/pykms/db:/home/py-kms/db"
      - /etc/localtime:/etc/localtime:ro
  when: docker_image.changed
  register: container_pykms

