# Readarr has been archived/retired.
# Keeping this for history
# ---
# - name: Create directories
#   file:
#     path: "{{ item }}"
#     state: directory
#   with_items:
#     - "/data/readarr"
#     - "/data/readarr/config"

# - name: Create the readarr container
#   docker_container:
#     name: readarr
#     image: linuxserver/readarr:develop@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
#     restart_policy: unless-stopped
#     recreate: true
#     networks:
#       - name: proxy
#     env:
#       PUID: "1000"
#       PGID: "1000"
#       TZ: "Australia/Brisbane"
#       DOCKER_MODS: "ghcr.io/themepark-dev/theme.park:readarr"
#     volumes:
#       - "/data/readarr/config/:/config"
#       - /mnt/nfs/data/:/data
#     labels:
#       traefik.enable: "true"
#       traefik.http.routers.readarr.rule: "Host(`readarr.comprofix.xyz`)"
#       traefik.http.routers.readarr.entrypoints: "https"
#       traefik.http.routers.readarr.tls: "true"
#       traefik.http.services.readarr.loadbalancer.server.port: "8787"
