---
- name: Find all EXTERNALLY-MANAGED files under /usr/lib/python*
  find:
    paths: /usr/lib
    patterns: "EXTERNALLY-MANAGED"
    file_type: file
    recurse: yes
  register: externally_managed_files
  become: yes

- name: Delete EXTERNALLY-MANAGED files
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ externally_managed_files.files }}"
  when: externally_managed_files.matched > 0
  become: yes
